### ISSUE TITLE
English translation of Scout v2.0 protocol documentation?

### ISSUE THREAD

**Issue by rarmstrong22** [westonrobot/ugv_sdk#18]

**Comment by rdu-weston** [comment]
FYI: you can find documentations here:
https://github.com/agilexrobotics/AgileX-Robotics-all-products-user-manuals/blob/master/UserGuider_EN.md

**Comment by rarmstrong22** [comment]
Hello,
Thanks for the response. We've seen the translated User Manual, but we're hoping to get the protocol document in English.
Thanks,
Rick

**Comment by rdu-weston** [comment]
> Hello, Thanks for the response. We've seen the translated User Manual, but we're hoping to get the protocol document in English. Thanks, Rick
> 
> P.S. This one: https://github.com/agilexrobotics/ugv_sdk/blob/next/docs/protocol_v2/SCOUT%202.0%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C_210630.pdf

You can find it here: 

https://agilexrobotics.gitbook.io/scout2.0/3-getting-started#3.3-communication-using-can

**Comment by rarmstrong22** [comment]
We're looking specifically for the command to disable/enable servo brakes. We mostly operate on flat ground, and the servo braking subsystem consumes too much current at idle for our purpose. 
I now see this in the `agilex_base.hpp`; does this do what we want (Scout 2.0 platform)?:
`
  void SetBrakeMode(BrakeMode mode);
`

**Comment by rdu-weston** [comment]
> We're looking specifically for the command to disable/enable servo brakes. We mostly operate on flat ground, and the servo braking subsystem consumes too much current at idle for our purpose. I now see this in `agilex_base.hpp`; does this do what we want (Scout 2.0 platform)?: `void SetBrakeMode(BrakeMode mode);`

Unfortunately it's not. SetBrakeMode() function is for a different robot model other than Scout. Due to the similarities in communication among different robot models, agilex_base.hpp handles all possible communication messages at one place to avoid duplicating code for each robot. Only functions exposed in [ugv_sdk/mobile_robot/scout_robot.hpp](https://github.com/westonrobot/ugv_sdk/tree/main/include/ugv_sdk/mobile_robot/scout_robot.hpp) are valid for Scout.

At the moment, the function you want is not available and it's only possible to achieve that by talking directly to the motor driver. However, controlling motor drivers directly is potentially dangerous and incorrect command may cause damage to the hardware. That's why it's not planned to be exposed to the customers.

Can you send us an email and let us know where you're based (which country)? We can discuss and evaluate whether we can come up with a solution.

**Comment by rarmstrong22** [comment]
> Can you send us an email ([support@westonrobot.com](mailto:support@westonrobot.com)) and let us know where you're based (which country)? We can discuss and evaluate whether we can come up with a solution.

Will do; thanks.
