### ISSUE TITLE
Scout 2.0 doesn't resume moving if restarted while ROS is operational

### ISSUE THREAD

**Issue by tiwaojo** [westonrobot/ugv_sdk#51]
Hello, I have an issue relating to the CAN Interface and the Scout 2.0 model. I am using ROS2 and following the instructions as described [here](https://github.com/agilexrobotics/ugv_sdk?tab=readme-ov-file#setup-can-to-usb-adapter) to setup the canbus. My robot fails to resume motion once restarted. I have narrowed down the issue to the CAN interface. `candump can0` works as expected before and after restarting the robot.

## Steps to reproduce
- Setup CAN-To-USB adapter
- Launch scout_ros2
- In another terminal run `ros2 topic pub -r 10 /cmd_vel geometry_msgs/Twist  '{linear:  {x: 0.4, y: 0.0, z: 0.0}, angular: {x: 0.0,y: 0.0,z: 0.1}}'`
- Interrupt normal operation by restarting the robot
- Robot wheels are no longer moving

## Expected Behaviour
- Upon restarting the robot, the ROS node should resume sending CAN frames to the robot and the wheels should be turning.

## Actual Behaviour
- Upon restarting the robot, the program continues as expected but the robot wheels no longer turn.
- A full restart of the ROS node is required

## System
- ROS2 Humble
- Ubuntu 22.04.4 LTS
- RMW Implementation: cyclonedds
- `libasio-dev` Version: 1:1.18.1-1
- `can-utils` Version: 2020.11.0-1

**Comment by karthee-weston** [comment]
Hi, 
The behaviour you described is expected. When the robot is switched on, it defaults to standby mode. Launching the ROS node then enables control using the scout_ros2 SDK.

This can lead to the robot remaining in standby mode if it's power cycled while the ROS node is running. Since the ROS node only enables control upon launch, the robot loses the control enable signal when powered off and doesn't regain it on restart.

The fix for this has been made in commit [34bf5dfaf8b1c8f2dd08d19790d0eead16bfb791](https://github.com/westonrobot/scout_ros2/commit/34bf5dfaf8b1c8f2dd08d19790d0eead16bfb791) under scout_ros2. A new ROS parameter named auto_reconnect has been introduced. When set to true, the node will attempt to re-establish control using the scout_ros2 SDK.

**Comment by tiwaojo** [comment]
Thank you. This solves my problem. I had begun looking into the CAN interface and the sockets implementation [here](https://github.com/westonrobot/ugv_sdk/blob/main/src/async_port/async_can.cpp) with the assumption that the socket "expires" as the port doesn't close when the robot restarts.
