### ISSUE TITLE
modprobe: FATAL: Module gs_usb not found in directory /lib/modules/5.15.136-tegra

### ISSUE THREAD

**Issue by nrose171** [westonrobot/ugv_sdk#58]
I am using a Jetson with JetPack 6.0 running ROS2 Humble. The repo builds fine, but the gs_usb module cannot be found in the kernel. Please let me know if there are any solutions to this. Thank you.
![UGV_ERROR](https://github.com/user-attachments/assets/f3c78149-b118-49f1-8bf1-f8824c7921e5)

**Comment by rdu-weston** [comment]
Hi, for the CAN bus issue you have, there are two possible solutions:
1) manually build and install the gs_usb kernel module to your system
2) if your jetson board has physical CAN controller, you may consider using the native CAN hardware instead of the USB adapter (you may need to add a CAN transceiver if you're using a Jetson devkit which doesn't have the transceiver integrated on the board by default)

**Comment by nrose171** [comment]
Thanks for the quick reply! I was able to fix this issue by following these instructions: [https://forums.developer.nvidia.com/t/missing-gs-usb-kernel-module-for-jetpack-6/275287/7](https://forums.developer.nvidia.com/t/missing-gs-usb-kernel-module-for-jetpack-6/275287/7)

**Comment by daeunSong** [comment]
Hello @nrose171, we are encountering the same issue with the gs_usb module not being found. 
We also tried rebuilding the kernel and reflashing the Jetson, but that introduced a new problem. The Wi-Fi and Ethernet ports were no longer being detected.

Can I ask what modules you have added to resolve this issue? Which version did you use to compare? 

Thanks!
